coverage:
  range: 60..80
  round: down
  precision: 2
  status:
    project:
      default:
        target: 70%
        threshold: 1%
    patch:
      target: 50%
      threshold: 10%

ignore:
  - "**/java/seedu/address/ui/**" # ignore test coverage on UI
