coverage:
  range: 60..80
  round: down
  precision: 2
  status:
    project:
      default:
        target: 80%
        threshold: 1%
ignore:
  - "**/java/seedu/address/ui/**/*" # ignore test coverage on UI
